service_mapping = {
        'Internal:Business Development':'BD support',
        'Rates:Principal Engineer/Director' : 'Studies/ Analysis (billable hours)',
        'Rates:Intern': 'Studies/ Analysis (billable hours)',
        'Rates:Executive Director' : 'Studies/ Analysis (billable hours)',
        'Rates:CAD Designer': 'Studies/ Analysis (billable hours)',
        'Rates:Assistant Application Engineer' : 'Studies/ Analysis (billable hours)',
        'Rates:Application Engineer' : 'Studies/ Analysis (billable hours)',
        'Rates:Admin Assistant': 'Studies/ Analysis (billable hours)',
        'Senior Engineer': 'Studies/ Analysis (billable hours)',
        'Internal:Proposals': 'Studies/ Analysis (billable hours)',
        'Internal:Internal Technical Project Discussion': 'Studies/ Analysis (billable hours)',
        'Internal:Internal Re-work': 'Studies/ Analysis (billable hours)',
        'Consulting': 'Studies/ Analysis (billable hours)',
        'Internal:Research':'Publications/ conferences/ panel discussions/ white papers/ webinars/ research',
        'Internal:Hiring' : 'People management (hiring/ mentoring/ engagement)',
        'Internal:Training & Development':'Trainings/ Self-development/ upskilling',
        'Internal:Self Development' :'Trainings/ Self-development/ upskilling',
        'Internal:Open hour':'Trainings/ Self-development/ upskilling',
        'Internal:Administrative':'Admin',
        'Internal:Admin - Meetings':'Admin',
        'Internal:Time off:Vacation Leave' : 'Time-off',
        'Internal:Time off:Compensatory time off' : 'Time-off',
        'Internal:Time off:Casual/Sick' : 'Time-off',
        'Internal:Time off:Holiday' : 'Time-off',
    }

team_mapping = {
        'Amritpal Singh':'Amritpal Singh',
        'C Praveen Kumar Reddy':'C Praveen Kumar Reddy',
        'Dr Suresh Singh':'Dr Suresh Singh',
        'Jigar Gorasiya': 'Jigar Gorasiya',
        'Sagar Savalia':'Sagar Savalia',
        'Vinoth Krishnan':'Vinoth Krishnan',
        'Abhilash Sharma':'C Praveen Kumar Reddy',
        'Adarsh P Pandey':'Dr Suresh Singh',
        'Alamanda Kumar': '',
        'Albino Sebastian': 'Jigar Gorasiya',
        'Amir Rostami': 'Jigar Gorasiya',
        'Amit Kumar':'Sagar Savalia',
        'Ankit  Raj':'C Praveen Kumar Reddy',
        'Ankit Singh':'Vinoth Krishnan',
        'Anuoluwapo Aluko': 'Jigar Gorasiya',
        'Anupama Narayanan':'Sagar Savalia',
        'Aprajita  Salgotra':'Vinoth Krishnan',
        'Ayushi Prajapati':'Dr Suresh Singh',
        'Ayushman Pal':'Sagar Savalia',
        'Bhaskar1 Vamsi':'Rama Satya Satish Kumar Vuppala',
        'Bollipo Ratnakar  Babu':'C Praveen Kumar Reddy',
        'Deepak Meena':'C Praveen Kumar Reddy',
        'Dilip Nehara':'Dr Suresh Singh',
        'Dinesh Kumar':'Dr Suresh Singh',
        'Etikikota Tharun':'C Praveen Kumar Reddy',
        'Garlapati Venkata Rao  Nikhil': 'C Praveen Kumar Reddy',
        'Godaba Venkata Radha Krishna': 'C Praveen Kumar Reddy',
        'Himanshu K Gupta':'Rama Satya Satish Kumar Vuppala',
        'Ibrar Hussain': '',
        'Indrajeet Bhavar':'Rama Satya Satish Kumar Vuppala',
        'Jeeva CS':'C Praveen Kumar Reddy',
        'Kalla Yamuna':'Sagar Savalia',
        'Kanav Minhas':'Dr Suresh Singh',
        'Kanika Kanika':'Sagar Savalia',
        'Kasireddi  Kumar':'C Praveen Kumar Reddy',
        'Lekhika Gupta':'Dr Suresh Singh',
        'MAV Silvester': '',
        'Manikandan V':'Sagar Savalia',
        'Maxwell P Mendonca':'Sagar Savalia',
        'Mohammed Bilal': '',
        'Mohan Raj':'Rama Satya Satish Kumar Vuppala',
        'Mubeena Nadarsha': '',
        'Muhammad Fanseem':'Rama Satya Satish Kumar Vuppala',
        'Navya HG': '',
        'Neha Gupta':'Dr Suresh Singh',
        'Nirupma Sharma':'Vinoth Krishnan',
        'Nitish Kumar':'Dr Suresh Singh',
        'Oggu Jeevana Jyothi': '',
        'Owais  Malla': 'Rama Satya Satish Kumar Vuppala',
        'Pittu Hanush':'C Praveen Kumar Reddy',
        'Priyanka Kushwaha': '',
        'Rakesh Kumar': '',
        'Rama Satya Satish Kumar Vuppala': 'Rama Satya Satish Kumar Vuppala',
        'Ramachandrarao Bezawada':'C Praveen Kumar Reddy',
        'Rashmi Kumari':'Vinoth Krishnan',
        'Rijo Raju': '',
        'Rita Singh': '',
        'Ritvik Salaria':'Sagar Savalia',
        'Roman K Jha':'Dr Suresh Singh',
        'Sadanand Aggarwal':'C Praveen Kumar Reddy',
        'Sarabjeet Bisla':'Rama Satya Satish Kumar Vuppala',
        'Sarthak Singh':'Dr Suresh Singh',
        'Savant Singh Dahiya': '',
        'Srihari  Santhosh':'Vinoth Krishnan',
        'Sumeet Kumar  Wankhede':'Dr Suresh Singh',
        'Sweety K Yadav':'Sagar Savalia',
        'Tarun Bharti':'Dr Suresh Singh',
        'Upasna  Kaushal':'Vinoth Krishnan',
        'Vamsi Krishna':'Rama Satya Satish Kumar Vuppala',
        'Vandana Jain':'Dr Suresh Singh',
        'Vidhya Sagar':'Rama Satya Satish Kumar Vuppala',
        'Vikramjit Singh': '',
        'Vishwagna Chari': '',
        'Vivek K Verma':'Rama Satya Satish Kumar Vuppala',
        'Yadukrishna KR':'Sagar Savalia'
    }